from typing import Annotated, overload

from numpy.typing import NDArray


class ExpAverage:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, /) -> None: ...

    def step(self, arg: Annotated[NDArray, dict(order='C', device='cpu')], /) -> None: ...

    @property
    def time_constant(self) -> float: ...

    @property
    def state(self) -> complex: ...

def decrement_it(arg: list, /) -> list: ...

def double_it(arg: list[int]) -> list[int]: ...

def square_it(arg: list[int]) -> list[int]: ...
